#
#	server.markhome.mcf.CFSec
#
#	Copyright (c) 2016-2026 Mark Stephen Sobkow
#	
#	Mark's Code Fractal 3.1 CFSec - Security Services
#	
#	Copyright (c) 2016-2026 Mark Stephen Sobkow mark.sobkow@gmail.com
#	
#	These files are part of Mark's Code Fractal CFSec.
#	
#	Licensed under the Apache License, Version 2.0 (the "License");
#	you may not use this file except in compliance with the License.
#	You may obtain a copy of the License at
#	
#	http://www.apache.org/licenses/LICENSE-2.0
#	
#	Unless required by applicable law or agreed to in writing, software
#	distributed under the License is distributed on an "AS IS" BASIS,
#	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#	See the License for the specific language governing permissions and
#	limitations under the License.
#	
#
cfsec.javafx.Cluster.AttrPane.Id.EffLabel=Id
cfsec.javafx.Cluster.AttrPane.FullDomName.EffLabel=Full Domain Name
cfsec.javafx.Cluster.AttrPane.Description.EffLabel=Cluster Description
cfsec.javafx.HostNode.AttrPane.HostNodeId.EffLabel=Host Node Id
cfsec.javafx.HostNode.AttrPane.Description.EffLabel=Description
cfsec.javafx.HostNode.AttrPane.HostName.EffLabel=Host Name
cfsec.javafx.HostNode.AttrPane.ContainerCluster.EffLabel=Cluster
cfsec.javafx.ISOCcy.AttrPane.ISOCcyId.EffLabel=ISOCcyId
cfsec.javafx.ISOCcy.AttrPane.ISOCode.EffLabel=ISOCode
cfsec.javafx.ISOCcy.AttrPane.Name.EffLabel=Name
cfsec.javafx.ISOCcy.AttrPane.UnitSymbol.EffLabel=UnitSymbol
cfsec.javafx.ISOCcy.AttrPane.Precis.EffLabel=Precis
cfsec.javafx.ISOCcy.AttrPane.ChildrenCtry.EffLabel=Ctry
cfsec.javafx.ISOCtry.AttrPane.ISOCtryId.EffLabel=ISOCtryId
cfsec.javafx.ISOCtry.AttrPane.ISOCode.EffLabel=ISOCode
cfsec.javafx.ISOCtry.AttrPane.Name.EffLabel=Name
cfsec.javafx.ISOCtryCcy.AttrPane.ContainerCtry.EffLabel=Ctry
cfsec.javafx.ISOCtryCcy.AttrPane.ParentCcy.EffLabel=Ccy
cfsec.javafx.ISOCtryLang.AttrPane.ContainerCtry.EffLabel=Ctry
cfsec.javafx.ISOCtryLang.AttrPane.ParentLang.EffLabel=Lang
cfsec.javafx.ISOLang.AttrPane.ISOLangId.EffLabel=ISOLangId
cfsec.javafx.ISOLang.AttrPane.ISO6392Code.EffLabel=ISO6392Code
cfsec.javafx.ISOLang.AttrPane.ISO6391Code.EffLabel=ISO6391Code
cfsec.javafx.ISOLang.AttrPane.EnglishName.EffLabel=EnglishName
cfsec.javafx.ISOLang.AttrPane.ChildrenCtry.EffLabel=Ctry
cfsec.javafx.ISOTZone.AttrPane.ISOTZoneId.EffLabel=ISO Timezone Id
cfsec.javafx.ISOTZone.AttrPane.Iso8601.EffLabel=ISO8601
cfsec.javafx.ISOTZone.AttrPane.TZName.EffLabel=Timezone Name
cfsec.javafx.ISOTZone.AttrPane.TZHourOffset.EffLabel=Timezone Hour Offset
cfsec.javafx.ISOTZone.AttrPane.TZMinOffset.EffLabel=Timezone Minute Offset
cfsec.javafx.ISOTZone.AttrPane.Description.EffLabel=Description
cfsec.javafx.ISOTZone.AttrPane.Visible.EffLabel=Visible
cfsec.javafx.SecDevice.AttrPane.DevName.EffLabel=Device Name
cfsec.javafx.SecDevice.AttrPane.ContainerSecUser.EffLabel=Security User
cfsec.javafx.SecGroup.AttrPane.SecGroupId.EffLabel=Security Group Id
cfsec.javafx.SecGroup.AttrPane.Name.EffLabel=Name
cfsec.javafx.SecGroup.AttrPane.IsVisible.EffLabel=IsVisible
cfsec.javafx.SecGroup.AttrPane.ContainerCluster.EffLabel=Cluster
cfsec.javafx.SecGroup.AttrPane.ChildrenIncByGroup.EffLabel=Included By Group
cfsec.javafx.SecGrpInc.AttrPane.SecGrpIncId.EffLabel=Security Group Include Id
cfsec.javafx.SecGrpInc.AttrPane.ContainerGroup.EffLabel=Group
cfsec.javafx.SecGrpInc.AttrPane.ParentSubGroup.EffLabel=SubGroup
cfsec.javafx.SecGrpMemb.AttrPane.SecGrpMembId.EffLabel=Security Group Member Id
cfsec.javafx.SecGrpMemb.AttrPane.ContainerGroup.EffLabel=Group
cfsec.javafx.SecGrpMemb.AttrPane.ParentUser.EffLabel=User
cfsec.javafx.SecSession.AttrPane.SecSessionId.EffLabel=Security Session Id
cfsec.javafx.SecSession.AttrPane.SecUserId.EffLabel=Security User Id
cfsec.javafx.SecSession.AttrPane.SecDevName.EffLabel=Sesion Device Name
cfsec.javafx.SecSession.AttrPane.Start.EffLabel=Start
cfsec.javafx.SecSession.AttrPane.Finish.EffLabel=Finish
cfsec.javafx.SecSession.AttrPane.SecProxyId.EffLabel=Security Proxy User Id
cfsec.javafx.SecUser.AttrPane.SecUserId.EffLabel=Security User Id
cfsec.javafx.SecUser.AttrPane.LoginId.EffLabel=Login Id
cfsec.javafx.SecUser.AttrPane.EMailAddress.EffLabel=EMail Address
cfsec.javafx.SecUser.AttrPane.EMailConfirmUuid6.EffLabel=EMail Confirm UUID6
cfsec.javafx.SecUser.AttrPane.PasswordHash.EffLabel=Password Hash
cfsec.javafx.SecUser.AttrPane.PasswordResetUuid6.EffLabel=Password Reset UUID6
cfsec.javafx.SecUser.AttrPane.LookupDefDev.EffLabel=Default Security Device
cfsec.javafx.SecUser.AttrPane.ChildrenSecGrpMemb.EffLabel=Security Group Members
cfsec.javafx.SecUser.AttrPane.ChildrenTSecGrpMemb.EffLabel=Tenant Security Group Members
cfsec.javafx.Service.AttrPane.ServiceId.EffLabel=Service Id
cfsec.javafx.Service.AttrPane.HostPort.EffLabel=Host Port
cfsec.javafx.Service.AttrPane.ContainerHost.EffLabel=Host
cfsec.javafx.Service.AttrPane.ParentServiceType.EffLabel=Service Type
cfsec.javafx.ServiceType.AttrPane.ServiceTypeId.EffLabel=Service Type Id
cfsec.javafx.ServiceType.AttrPane.Description.EffLabel=Description
cfsec.javafx.ServiceType.AttrPane.ChildrenDeployed.EffLabel=Deployed
cfsec.javafx.SysCluster.AttrPane.SingletonId.EffLabel=Singleton
cfsec.javafx.SysCluster.AttrPane.ContainerCluster.EffLabel=Cluster
cfsec.javafx.Tenant.AttrPane.Id.EffLabel=Id
cfsec.javafx.Tenant.AttrPane.TenantName.EffLabel=TenantName
cfsec.javafx.Tenant.AttrPane.ContainerCluster.EffLabel=Cluster
cfsec.javafx.TSecGroup.AttrPane.TSecGroupId.EffLabel=TSecurity Group Id
cfsec.javafx.TSecGroup.AttrPane.Name.EffLabel=Name
cfsec.javafx.TSecGroup.AttrPane.IsVisible.EffLabel=IsVisible
cfsec.javafx.TSecGroup.AttrPane.ContainerTenant.EffLabel=Tenant
cfsec.javafx.TSecGroup.AttrPane.ChildrenIncByGroup.EffLabel=Included By Group
cfsec.javafx.TSecGrpInc.AttrPane.TSecGrpIncId.EffLabel=TSecurity Group Include Id
cfsec.javafx.TSecGrpInc.AttrPane.ContainerGroup.EffLabel=Group
cfsec.javafx.TSecGrpInc.AttrPane.ParentSubGroup.EffLabel=SubGroup
cfsec.javafx.TSecGrpMemb.AttrPane.TSecGrpMembId.EffLabel=TSecurity Group Member Id
cfsec.javafx.TSecGrpMemb.AttrPane.ContainerGroup.EffLabel=Group
cfsec.javafx.TSecGrpMemb.AttrPane.ParentUser.EffLabel=User
